name: Release

on:
    workflow_dispatch:


jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v1

            - name: Release
              run: |
                  python3 -m pip install pipenv
                  TWINE_USERNAME="$TWINE_USERNAME" \
                  TWINE_PASSWORD="$TWINE_PASSWORD" \
                  make publish
